name: CI/CD for Classifier API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3) Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my_classifier_api:${{ github.sha }} .

      # 4) Tag as latest
      - name: Tag as latest
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/my_classifier_api:${{ github.sha }} \
                     ${{ secrets.DOCKERHUB_USERNAME }}/my_classifier_api:latest

      # 5) Push Docker images (SHA, latest)
      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my_classifier_api:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my_classifier_api:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'   # Deploy only when merged to main branch

    steps:
      # 1) Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Connect to remote server via SSH and restart container
      - name: Deploy to remote server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my_classifier_api:latest
            docker stop my_classifier_container || true
            docker rm my_classifier_container || true
            docker run -d --name my_classifier_container -p 8000:8000 \
              ${{ secrets.DOCKERHUB_USERNAME }}/my_classifier_api:latest